# Generated by Django 4.2 on 2024-10-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField()),
                ('code', models.CharField(blank=True, max_length=10)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
